import type { ThemePreset } from '@/types'

export const themePresets: Record<string, ThemePreset> = {
  japan: {
    primary: '#F4B8C1',
    accent: '#1a1a2e',
    background: '#fdf6f7',
    cardBg: '#fff8f9',
    text: '#1a1a2e',
    subtle: '#9e7d82',
    fontMood: 'minimal',
    bgStyle: 'clean',
  },
  morocco: {
    primary: '#C1440E',
    accent: '#F4A528',
    background: '#1a0a00',
    cardBg: '#2a1200',
    text: '#f5e6d0',
    subtle: '#c49a6c',
    fontMood: 'warm',
    bgStyle: 'geometric',
  },
  scandinavia: {
    primary: '#B8D4E8',
    accent: '#F5F0E8',
    background: '#0d1b2a',
    cardBg: '#162233',
    text: '#e8f0f5',
    subtle: '#7a9ab5',
    fontMood: 'minimal',
    bgStyle: 'clean',
  },
  brazil: {
    primary: '#2D6A4F',
    accent: '#F4D03F',
    background: '#0a1f14',
    cardBg: '#122a1c',
    text: '#e8f5ee',
    subtle: '#5a9e7a',
    fontMood: 'bold',
    bgStyle: 'gradient',
  },
  greece: {
    primary: '#1B4F8A',
    accent: '#F8F5F0',
    background: '#0a1929',
    cardBg: '#102238',
    text: '#e8f0f8',
    subtle: '#5a85b5',
    fontMood: 'elegant',
    bgStyle: 'clean',
  },
  india: {
    primary: '#FF6B35',
    accent: '#7B2D8B',
    background: '#1a0a00',
    cardBg: '#2a1200',
    text: '#ffeedd',
    subtle: '#cc8866',
    fontMood: 'vibrant',
    bgStyle: 'geometric',
  },
  'southeast-asia': {
    primary: '#4A7C59',
    accent: '#E8A838',
    background: '#0d1a10',
    cardBg: '#162318',
    text: '#e8f0e8',
    subtle: '#7aaa88',
    fontMood: 'warm',
    bgStyle: 'gradient',
  },
  mediterranean: {
    primary: '#C17A5A',
    accent: '#2A9D8F',
    background: '#1a0e08',
    cardBg: '#261510',
    text: '#f5ede8',
    subtle: '#a87a60',
    fontMood: 'warm',
    bgStyle: 'gradient',
  },
  caribbean: {
    primary: '#0CB4D5',
    accent: '#FF6B6B',
    background: '#00151c',
    cardBg: '#001e28',
    text: '#e0f8ff',
    subtle: '#4abcd5',
    fontMood: 'vibrant',
    bgStyle: 'gradient',
  },
  'east-africa': {
    primary: '#C9A84C',
    accent: '#4A2E1A',
    background: '#0f0a04',
    cardBg: '#1a1208',
    text: '#f5edd0',
    subtle: '#a0824a',
    fontMood: 'warm',
    bgStyle: 'noise',
  },
  'middle-east': {
    primary: '#B8860B',
    accent: '#800020',
    background: '#0a0800',
    cardBg: '#160f02',
    text: '#f5edd0',
    subtle: '#9a7030',
    fontMood: 'elegant',
    bgStyle: 'geometric',
  },
  'central-europe': {
    primary: '#355E3B',
    accent: '#8B7355',
    background: '#0a0f0a',
    cardBg: '#121812',
    text: '#e8f0e8',
    subtle: '#6a8a6a',
    fontMood: 'bold',
    bgStyle: 'clean',
  },
  default: {
    primary: '#1B2B4B',
    accent: '#F59E0B',
    background: '#0a0f1e',
    cardBg: '#111827',
    text: '#f0f4ff',
    subtle: '#6b7a99',
    fontMood: 'elegant',
    bgStyle: 'gradient',
  },
}

export const weatherModifiers: Record<string, string> = {
  Clear: 'brightness(1.1) saturate(1.15)',
  Clouds: 'brightness(0.95) saturate(0.9)',
  Rain: 'brightness(0.85) saturate(0.8) hue-rotate(10deg)',
  Drizzle: 'brightness(0.85) saturate(0.8) hue-rotate(10deg)',
  Snow: 'brightness(1.05) saturate(0.7)',
  Thunderstorm: 'brightness(0.75) saturate(1.2) contrast(1.1)',
  Mist: 'brightness(0.9) saturate(0.75)',
}

// Maps country regions from the database to our theme preset keys
export const regionToTheme: Record<string, string> = {
  'Eastern Asia': 'japan',
  'South-Eastern Asia': 'southeast-asia',
  'Southern Asia': 'india',
  'Northern Africa': 'morocco',
  'Western Africa': 'east-africa',
  'Eastern Africa': 'east-africa',
  'Southern Africa': 'east-africa',
  'Middle Africa': 'east-africa',
  'Northern Europe': 'scandinavia',
  'Southern Europe': 'mediterranean',
  'Western Europe': 'central-europe',
  'Eastern Europe': 'central-europe',
  'South America': 'brazil',
  'Central America': 'caribbean',
  'Caribbean': 'caribbean',
  'Western Asia': 'middle-east',
  'Australia and New Zealand': 'scandinavia',
}

export function getThemeForRegion(region: string): ThemePreset {
  const key = regionToTheme[region] ?? 'default'
  return themePresets[key] ?? themePresets.default
}
